# Generated by Django 5.1.6 on 2025-04-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_productview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
    ]
