# Generated by Django 5.1.6 on 2025-04-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_userworkouthistory_repetitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerrating',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
