# Generated by Django 5.1.6 on 2025-05-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_trainerrating_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
