# Generated by Django 5.1.6 on 2025-05-02 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workout_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupworkout',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trainerrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')], default=1),
        ),
        migrations.AlterField(
            model_name='userworkoutsignup',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='workouts.workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='capacity',
            field=models.PositiveIntegerField(default=20, help_text='Max participants'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='workoutreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='groupworkoutparticipant',
            unique_together={('group_workout', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userworkoutsignup',
            unique_together={('user', 'workout')},
        ),
    ]
