# Generated by Django 5.1.6 on 2025-05-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20250502_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
